<?php
namespace ParthShukla\UserManagement\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use ParthShukla\UserManagement\Listeners\SendAccountStatusChangedEmail;
use ParthShukla\UserManagement\Events\UserAccountStatusUpdated;

/**
 * EventServiceProvider class
 *
 * @since 1.0.0
 * @version 1.0.0
 * @author Parth Shukla <parthshukla@ahex.co.in>
 */
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        UserAccountStatusUpdated::class => [
            SendAccountStatusChangedEmail::class
        ]
    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
// end of class EventServiceProvider
// end of file EventServiceProvider.php
